web/app/config/routes.rb
Rails.application.routes.draw do

  devise_for :managers, path: 'admin/managers', controllers: {
    sessions: 'admin/managers/sessions'
  }

  # 管理者画面系
  namespace :admin do
    root 'home#index'
  end

  # Coupyページ
  scope module: :page do
    root 'home#index'
    resources :keywords
    post '/callback', to: 'linebot#callback'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

web/app/app/models/keyword.rb
class Keyword < ApplicationRecord
end

web/app/app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]

  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: 'Keyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keyword_params
      params.require(:keyword).permit(:send_msg, :response_msg)
    end
end

web/app/app/controllers/page/keywords_controller.rb
class Page::KeywordsController < Page::BaseController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]

  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: 'Keyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keyword_params
      params.require(:keyword).permit(:send_msg, :response_msg)
    end
end

web/app/app/helpers/keywords_helper.rb
module KeywordsHelper
end

web/app/app/views/page/keywords/_form.html.erb
<%= form_with(model: keyword, local: true) do |form| %>
  <% if keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% keyword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :send_msg %>
    <%= form.text_field :send_msg, id: :keyword_send_msg %>
  </div>

  <div class="field">
    <%= form.label :response_msg %>
    <%= form.text_field :response_msg, id: :keyword_response_msg %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

web/app/app/views/page/keywords/edit.html.erb
<h1>Editing Keyword</h1>

<%= render 'form', keyword: @keyword %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

web/app/app/views/page/keywords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Keywords</h1>

<table>
  <thead>
    <tr>
      <th>Send msg</th>
      <th>Response msg</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><%= keyword.send_msg %></td>
        <td><%= keyword.response_msg %></td>
        <td><%= link_to 'Show', keyword %></td>
        <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
        <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Keyword', new_keyword_path %>

web/app/app/views/page/keywords/new.html.erb
<h1>New Keyword</h1>

<%= render 'form', keyword: @keyword %>

<%= link_to 'Back', keywords_path %>

web/app/app/views/page/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Send msg:</strong>
  <%= @keyword.send_msg %>
</p>

<p>
  <strong>Response msg:</strong>
  <%= @keyword.response_msg %>
</p>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>